version: "3.4"
services:
  api:
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_URL: postgres://postgres:db_dev_pass@db:5432/postgres
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app
    command: npx nodemon --watch src --exec "clear && (npm run lint:src & node index.js)"
  db:
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: db_dev_pass