version: "3.4"
services:
  api:
    image: ${DOCKER_IMAGE_NAME}
    depends_on:
      - db
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres:10-alpine
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
networks:
  backend: