version: "3.2"
services:
  api:
    image: rafamel/rest-api
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_URL: postgres://postgres@db:5432/postgres
    deploy:
      restart_policy:
        condition: on-failure
  db:
    image: postgres:10-alpine
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
networks:
  backend: